CREATE OR REPLACE TRIGGER time_create_country
BEFORE INSERT OR UPDATE OF time_create
ON country
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_city
BEFORE INSERT OR UPDATE OF time_create
ON city
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_street
BEFORE INSERT OR UPDATE OF time_create
ON street
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_address
BEFORE INSERT OR UPDATE OF time_create
ON address
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_car
BEFORE INSERT OR UPDATE OF time_create
ON car
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_currency
BEFORE INSERT OR UPDATE OF time_create
ON currency
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_curr2cntry
BEFORE INSERT OR UPDATE OF time_create
ON currency2country
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_driver
BEFORE INSERT OR UPDATE OF time_create
ON driver
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_driver$Image
BEFORE INSERT OR UPDATE OF time_create
ON driver_image
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_driver$Rating
BEFORE INSERT OR UPDATE OF time_create
ON driver_rating
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_order$Information
BEFORE INSERT OR UPDATE OF time_create
ON order_information
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_parking
BEFORE INSERT OR UPDATE OF time_create
ON parking
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_passenger
BEFORE INSERT OR UPDATE OF time_create
ON passenger
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_passenger$Image
BEFORE INSERT OR UPDATE OF time_create
ON passenger_image
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_passenger$Rating
BEFORE INSERT OR UPDATE OF time_create
ON passenger_rating
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_payment
BEFORE INSERT OR UPDATE OF time_create
ON payment
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER time_create_rate
BEFORE INSERT OR UPDATE OF time_create
ON rate
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER Insert$Update_row
BEFORE INSERT OR UPDATE OF time_create
ON rayting_driver2pass
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER Insert$Update_rows
BEFORE INSERT OR UPDATE OF time_create
ON rayting_pass2driver
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER Insert$Update_rows2
BEFORE INSERT OR UPDATE OF time_create
ON refueling_station
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER Insert$Update_rows3
BEFORE INSERT OR UPDATE OF time_create
ON rent_car
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
CREATE OR REPLACE TRIGGER Insert$Update_rows4
BEFORE INSERT OR UPDATE OF time_create
ON way
FOR EACH ROW
BEGIN
IF INSERTING
    THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
ELSIF UPDATING THEN
    :NEW.TIME_CREATE:=TO_TIMESTAMP(SYSDATE);
END IF;
END;
/
